#!/bin/bash

set -e

KSK_PATTERN="(56676|64441)"
DS_NSERVER="172.20.1.18"

fix_dns() {
	SRC="$1"
	DST="$2"
	{
		echo "domain:             ${DST}"
		cat "data/dns/${SRC}" | grep '^nserver:' | tr -s " " | cut -d' ' -f2 | sort | uniq | xargs -i echo 'nserver:            {}'
		drill -t "${DST}" "@${DS_NSERVER}" DNSKEY -s | grep sha256 | cut -d: -f2 | sed -E 's/^ [^\t ]+\t900\tIN\tDS\t/ds-rdata:           /g' | grep -E "${KSK_PATTERN}"
		echo 'org:                ORG-DN42'
		echo 'mnt-by:             DN42-MNT'
		echo 'source:             DN42'
	} > "data/dns/${DST}"
}

fix_inetnum() {
	SRC="$1"
	DST="$2"
	CLASS="$3"
	POLICY="$4"
	DNS_NAME="$5"
	if [ -f "data/${CLASS}/${DST}" ]; then
		sed -r -i '/^(nserver|ds-rdata|status|org|policy|mnt-by|source|admin-c|tech-c):.*$/d' "data/${CLASS}/${DST}"
		{
			cat "data/dns/${SRC}" | grep '^nserver:' | tr -s " " | cut -d' ' -f2 | sort | uniq | xargs -i echo 'nserver:            {}'
			drill -t "${DNS_NAME}" "@${DS_NSERVER}" DNSKEY -s | grep sha256 | cut -d: -f2 | sed -E 's/^ [^\t ]+\t900\tIN\tDS\t/ds-rdata:           /g' | grep -E "${KSK_PATTERN}"
			echo 'status:             ALLOCATED'
			echo "policy:             ${POLICY}"
			echo 'org:                ORG-DN42'
			echo 'mnt-by:             DN42-MNT'
			echo 'source:             DN42'
		} >> "data/${CLASS}/${DST}"
	fi
}

fix_dns 'delegation-servers.dn42' 'dn42'
fix_inetnum 'delegation-servers.dn42' 'fd00::_8' 'inet6num' 'open' 'd.f.ip6.arpa'
fix_inetnum 'delegation-servers.dn42' '10.0.0.0_8' 'inetnum' 'closed' '10.in-addr.arpa'
for i in 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31; do
	fix_inetnum 'delegation-servers.dn42' "172.${i}.0.0_16" 'inetnum' 'closed' "${i}.172.in-addr.arpa"
done

